# swagger.yml

openapi: 3.0.0
info:
  title: "RP Flask REST API"
  description: "An API about people and notes"
  version: "1.0.0"

servers:
  - url: "/api"

components:

  schemas:

    User:
      type: "object"
      properties:
        first_name:
          type: "string"
        age:
          type: "integer"
        id_:
          type: "integer"
        phone_numbers:
          type: array
          items:
              type: object
        gender:
          type: "string"
        last_name:
          type: "string"
        address:
          type: "object"
  parameters:
    id_:
      name: "user_id"
      description: "id of the user"
      in: path
      required: True
      schema:
        type: "string"

paths:
  /users:
    get:
      operationId: "APIS.get_users"
      tags:
        - "Users"
      summary: "list all the Users"
      responses:
        "200":
          description: "Successfully listed the users"
    post:
      operationId: "APIS.add_user"
      tags:
        - "Users"
      summary: "add a User"
      requestBody:
        description: "user info"
        required: True
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"


      responses:
        "201":
          description: "Successfully created person"
        "404":
          description: "failure"
  /users/{user_id}:
    get:
      operationId: "APIS.get_user_with_id"
      tags:
        - Users
      summary: "get the user with the entered id"
      parameters:
        - $ref: "#/components/parameters/id_"
      responses:
        "200":
          description: "Successfully found the user"
        "404":
          description: "failure"
    put:
      operationId: "APIS.update_user"
      tags:
        - Users
      summary: "update the user with the entered id"
      parameters:
        - $ref: "#/components/parameters/id_"
      requestBody:
        description: "new user info"
        required: True
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        "201":
          description: "Successfully updated"
        "404":
          description: "failure"
    delete:
      operationId: "APIS.del_user"
      tags:
        - Users
      summary: "delete the user with the entered id"
      parameters:
        - $ref: "#/components/parameters/id_"
      responses:
        "202":
          description: "Successfully deleted"
        "404":
          description: "failure"